### ISSUE TITLE
활성화 바랍니다.

### ISSUE THREAD

**Issue by kanghyun-eca21b** [eca21y/HelpDesk#10]
org: eca21b

repo: eca21b-nmisp-kanghyun-eca21b

url: https://github.com/eca21b/eca21b-nmisp-kanghyun-eca21b

**Comment by kangwon-naver** [comment]
org: eca21b
repo: eca21b-nmisp-kanghyun-eca21b
Processing request above

**Comment by kanghyun-eca21b** [comment]
org: eca21b
repo: eca21b-nmisp-kanghyun-eca21b

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Please check org : eca21b

**Comment by kangwonlee** [comment]
org: eca21y
repo: eca21b-nmisp-kanghyun-eca21b

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Please check whether the repo exists
https://github.com/eca21y/eca21b-nmisp-kanghyun-eca21b
