### ISSUE TITLE
활성화 바랍니다

### ISSUE THREAD

**Issue by yunjuneca20b** [eca21y/HelpDesk#106]
org: eca21y
repo: eca21y-00-00-00-yunjuneca20b
url: https://github.com/eca21y/eca21y-00-00-00-yunjuneca20b

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Please check org : eca21b (expecting eca21y)

**Comment by kangwonlee** [comment]
org : eca21y
repo : eca21b-00-00-10-yunjuneca20b
https://github.com/eca21y/eca21b-00-00-10-yunjuneca20b

**Comment by kangwon-naver** [comment]
org: eca21y
repo: eca21b-00-00-10-yunjuneca20b
Processing request above
https://github.com/eca21y/eca21b-00-00-10-yunjuneca20b

**Comment by kangwon-naver** [comment]
org: eca21y
repo: eca21b-00-00-10-yunjuneca20b
Success! Start your engine!
https://github.com/eca21y/eca21b-00-00-10-yunjuneca20b
