### ISSUE TITLE
활성화바랍니다.

### ISSUE THREAD

**Issue by Guhyungjun** [eca21y/HelpDesk#195]
org: eca21y
repo: eca21b-00-20-70-Guhyungjun

**Comment by kangwon-naver** [comment]
org: eca21y
repo: eca21b-00-20-70-Guhyungjun
Processing request above
https://github.com/eca21y/eca21b-00-20-70-Guhyungjun

**Comment by kangwon-naver** [comment]
org: eca21y
repo: eca21b-00-20-70-Guhyungjun
Success! Start your engine!
https://github.com/eca21y/eca21b-00-20-70-Guhyungjun
