### ISSUE TITLE
활성화 시킵니다

### ISSUE THREAD

**Issue by Kimyongwoo-cdf21a** [eca21y/HelpDesk#51]
org: eca21b

repo:  eca21b-00-00-10-Kimyongwoo-cdf21a

url: https://github.com/eca21y/eca21b-00-00-10-Kimyongwoo-cdf21a

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Please check org : eca21b (expecting eca21y)

**Comment by Kimyongwoo-cdf21a** [comment]
org: eca21y

repo: eca21b-00-00-10-Kimyongwoo-cdf21a

url: https://github.com/eca21y/eca21b-00-00-10-Kimyongwoo-cdf21a
