### ISSUE TITLE
활성화바랍니다.

### ISSUE THREAD

**Issue by Kimyongwoo-cdf21a** [eca21y/HelpDesk#8]
org: eca21b

repo: eca21b-00-00-00-Kimyongwoo-cdf21a

url: https://github.com/eca21b/eca21b-00-00-00-Kimyongwoo-cdf21a

**Comment by kangwon-naver** [comment]
org: eca21b
repo: eca21b-00-00-00-Kimyongwoo-cdf21a
Processing request above

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Please check org : eca21b

**Comment by kangwonlee** [comment]
url https://github.com/eca21y/eca21b-00-00-10-Kimyongwoo-cdf21a 의 저장소는 이미 활성화 된 것으로 보입니다
위 org 에 eca21b 대신 eca21y 를 사용하면 해결되었을 것으로 보입니다
