### ISSUE TITLE
활성화바랍니다. (2018114012, 김진우)

### ISSUE THREAD

**Issue by kim66woo** [eca21y/HelpDesk#9]
org: eca21b
repo: eca21b-00-00-00-kim66woo

**Comment by kangwon-naver** [comment]
org: eca21b
repo: eca21b-00-00-00-kim66woo
Processing request above

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Please check org : eca21b

**Comment by kangwonlee** [comment]
org: eca21y
repo: eca21b-00-00-00-kim66woo

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Please check whether the repo exists
https://github.com/eca21y/eca21b-00-00-00-kim66woo

**Comment by kangwonlee** [comment]
@kim66woo 
https://github.com/eca21y 에서 보이는 학생의 저장소 가운데 하나를 입력 바랍니다
